; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = .

[env]
lib_ignore =
    slmp-connect-cpp-minimal
check_skip_packages = yes

[env:esp32-devkitc-low-level]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -Isrc
build_src_filter =
    +<src/slmp_minimal.cpp>
    +<examples/esp32_devkitc_low_level/esp32_devkitc_low_level.cpp>
check_src_filters =
    +<src/slmp_minimal.cpp>
    +<examples/esp32_devkitc_low_level/esp32_devkitc_low_level.cpp>

[env:esp32-devkitc-low-level-no-udp]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -Isrc
    -DSLMP_ENABLE_UDP_TRANSPORT=0
build_src_filter =
    +<src/slmp_minimal.cpp>
    +<examples/esp32_devkitc_low_level/esp32_devkitc_low_level.cpp>
check_src_filters =
    +<src/slmp_minimal.cpp>
    +<examples/esp32_devkitc_low_level/esp32_devkitc_low_level.cpp>

[env:esp32-devkitc-high-level]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -Isrc
build_src_filter =
    +<src/slmp_minimal.cpp>
    +<src/slmp_high_level.cpp>
    +<examples/esp32_devkitc_high_level/esp32_devkitc_high_level.cpp>
check_src_filters =
    +<src/slmp_minimal.cpp>
    +<src/slmp_high_level.cpp>
    +<examples/esp32_devkitc_high_level/esp32_devkitc_high_level.cpp>

[env:esp32-devkitc-polling-reconnect]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -Isrc
build_src_filter =
    +<src/slmp_minimal.cpp>
    +<src/slmp_high_level.cpp>
    +<examples/esp32_devkitc_polling_reconnect/esp32_devkitc_polling_reconnect.cpp>
check_src_filters =
    +<src/slmp_minimal.cpp>
    +<src/slmp_high_level.cpp>
    +<examples/esp32_devkitc_polling_reconnect/esp32_devkitc_polling_reconnect.cpp>

[env:wiznet-w6300-evb-pico2-polling-reconnect]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#f2877dd7844f8891231ad9fa69fd99921fe60466
board = wiznet_6300_evb_pico2
framework = arduino
monitor_speed = 115200
build_flags =
    -Isrc
build_src_filter =
    +<src/slmp_minimal.cpp>
    +<src/slmp_high_level.cpp>
    +<examples/wiznet_w6300_evb_pico2_polling_reconnect/wiznet_w6300_evb_pico2_polling_reconnect.cpp>
check_src_filters =
    +<src/slmp_minimal.cpp>
    +<src/slmp_high_level.cpp>
    +<examples/wiznet_w6300_evb_pico2_polling_reconnect/wiznet_w6300_evb_pico2_polling_reconnect.cpp>

[env:esp32-devkitc-high-level-no-udp]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -Isrc
    -DSLMP_ENABLE_UDP_TRANSPORT=0
build_src_filter =
    +<src/slmp_minimal.cpp>
    +<src/slmp_high_level.cpp>
    +<examples/esp32_devkitc_high_level/esp32_devkitc_high_level.cpp>
check_src_filters =
    +<src/slmp_minimal.cpp>
    +<src/slmp_high_level.cpp>
    +<examples/esp32_devkitc_high_level/esp32_devkitc_high_level.cpp>
