; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = .


[env:esp32-devkitc-low-level]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -Isrc
build_src_filter =
    +<src/slmp_minimal.cpp>
    +<examples/esp32_devkitc_low_level/esp32_devkitc_low_level.cpp>

[env:esp32-devkitc-low-level-no-udp]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -Isrc
    -DSLMP_ENABLE_UDP_TRANSPORT=0
build_src_filter =
    +<src/slmp_minimal.cpp>
    +<examples/esp32_devkitc_low_level/esp32_devkitc_low_level.cpp>

[env:esp32-devkitc-high-level]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -Isrc
build_src_filter =
    +<src/slmp_minimal.cpp>
    +<src/slmp_high_level.cpp>
    +<examples/esp32_devkitc_high_level/esp32_devkitc_high_level.cpp>

[env:esp32-devkitc-high-level-no-udp]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -Isrc
    -DSLMP_ENABLE_UDP_TRANSPORT=0
build_src_filter =
    +<src/slmp_minimal.cpp>
    +<src/slmp_high_level.cpp>
    +<examples/esp32_devkitc_high_level/esp32_devkitc_high_level.cpp>
