/**
 * @file slmp_error_codes.cpp
 * @brief Optional SLMP end-code symbolic names.
 */

#include "slmp_error_codes.h"

namespace slmp {

const char* endCodeString(uint16_t end_code) {
    switch (end_code) {
        case 0x1080:
            return "slmp_end_code_1080";
        case 0x1120:
            return "slmp_end_code_1120";
        case 0x1124:
            return "slmp_end_code_1124";
        case 0x1128:
            return "slmp_end_code_1128";
        case 0x1129:
            return "slmp_end_code_1129";
        case 0x112C:
            return "slmp_end_code_112c";
        case 0x112D:
            return "slmp_end_code_112d";
        case 0x112E:
            return "slmp_end_code_112e";
        case 0x1133:
            return "slmp_end_code_1133";
        case 0x1134:
            return "slmp_end_code_1134";
        case 0x1152:
            return "slmp_end_code_1152";
        case 0x1155:
            return "slmp_end_code_1155";
        case 0x1157:
            return "slmp_end_code_1157";
        case 0x1158:
            return "slmp_end_code_1158";
        case 0x1165:
            return "slmp_end_code_1165";
        case 0x1166:
            return "slmp_end_code_1166";
        case 0x1167:
            return "slmp_end_code_1167";
        case 0x1180:
            return "slmp_end_code_1180";
        case 0x1801:
            return "slmp_end_code_1801";
        case 0x1811:
            return "slmp_end_code_1811";
        case 0x1830:
            return "slmp_end_code_1830";
        case 0x1845:
            return "slmp_end_code_1845";
        case 0x1F07:
            return "slmp_end_code_1f07";
        case 0x20E0:
            return "slmp_end_code_20e0";
        case 0x2160:
            return "slmp_end_code_2160";
        case 0x2220:
            return "slmp_end_code_2220";
        case 0x2221:
            return "slmp_end_code_2221";
        case 0x2250:
            return "slmp_end_code_2250";
        case 0x24C0:
            return "slmp_end_code_24c0";
        case 0x24C1:
            return "slmp_end_code_24c1";
        case 0x24C2:
            return "slmp_end_code_24c2";
        case 0x24C3:
            return "slmp_end_code_24c3";
        case 0x24C6:
            return "slmp_end_code_24c6";
        case 0x3008:
            return "slmp_end_code_3008";
        case 0x3019:
            return "slmp_end_code_3019";
        case 0x301A:
            return "slmp_end_code_301a";
        case 0x301B:
            return "slmp_end_code_301b";
        case 0x301C:
            return "slmp_end_code_301c";
        case 0x301D:
            return "slmp_end_code_301d";
        case 0x301E:
            return "slmp_end_code_301e";
        case 0x3020:
            return "slmp_end_code_3020";
        case 0x3022:
            return "slmp_end_code_3022";
        case 0x3023:
            return "slmp_end_code_3023";
        case 0x3026:
            return "slmp_end_code_3026";
        case 0x3040:
            return "slmp_end_code_3040";
        case 0x3060:
            return "slmp_end_code_3060";
        case 0x3C00:
            return "slmp_end_code_3c00";
        case 0x3C01:
            return "slmp_end_code_3c01";
        case 0x3C02:
            return "slmp_end_code_3c02";
        case 0x3C03:
            return "slmp_end_code_3c03";
        case 0x3C0F:
            return "slmp_end_code_3c0f";
        case 0x3C10:
            return "slmp_end_code_3c10";
        case 0x3C11:
            return "slmp_end_code_3c11";
        case 0x3C13:
            return "slmp_end_code_3c13";
        case 0x3C14:
            return "slmp_end_code_3c14";
        case 0x3C2F:
            return "slmp_end_code_3c2f";
        case 0x3E01:
            return "slmp_end_code_3e01";
        case 0xC001:
            return "slmp_end_code_c001";
        case 0xC012:
            return "slmp_end_code_c012";
        case 0xC013:
            return "slmp_end_code_c013";
        case 0xC015:
            return "slmp_end_code_c015";
        case 0xC016:
            return "slmp_end_code_c016";
        case 0xC018:
            return "slmp_end_code_c018";
        case 0xC020:
            return "slmp_end_code_c020";
        case 0xC021:
            return "slmp_end_code_c021";
        case 0xC022:
            return "slmp_end_code_c022";
        case 0xC024:
            return "slmp_end_code_c024";
        case 0xC025:
            return "slmp_end_code_c025";
        case 0xC026:
            return "slmp_end_code_c026";
        case 0xC027:
            return "slmp_end_code_c027";
        case 0xC028:
            return "slmp_end_code_c028";
        case 0xC029:
            return "slmp_end_code_c029";
        case 0xC035:
            return "slmp_end_code_c035";
        case 0xC040:
            return "slmp_end_code_c040";
        case 0xC050:
            return "slmp_end_code_c050";
        case 0xC051:
            return "slmp_end_code_c051";
        case 0xC052:
            return "slmp_end_code_c052";
        case 0xC053:
            return "slmp_end_code_c053";
        case 0xC054:
            return "slmp_end_code_c054";
        case 0xC055:
            return "slmp_end_code_c055";
        case 0xC056:
            return "slmp_end_code_c056";
        case 0xC057:
            return "slmp_end_code_c057";
        case 0xC058:
            return "slmp_end_code_c058";
        case 0xC059:
            return "slmp_end_code_c059";
        case 0xC05A:
            return "slmp_end_code_c05a";
        case 0xC05B:
            return "slmp_end_code_c05b";
        case 0xC05C:
            return "slmp_end_code_c05c";
        case 0xC05D:
            return "slmp_end_code_c05d";
        case 0xC05E:
            return "slmp_end_code_c05e";
        case 0xC05F:
            return "slmp_end_code_c05f";
        case 0xC060:
            return "slmp_end_code_c060";
        case 0xC061:
            return "slmp_end_code_c061";
        case 0xC070:
            return "slmp_end_code_c070";
        case 0xC071:
            return "slmp_end_code_c071";
        case 0xC072:
            return "slmp_end_code_c072";
        case 0xC073:
            return "slmp_end_code_c073";
        case 0xC075:
            return "slmp_end_code_c075";
        case 0xC081:
            return "slmp_end_code_c081";
        case 0xC083:
            return "slmp_end_code_c083";
        case 0xC084:
            return "slmp_end_code_c084";
        case 0xC085:
            return "slmp_end_code_c085";
        case 0xC0B2:
            return "slmp_end_code_c0b2";
        case 0xC0B3:
            return "slmp_end_code_c0b3";
        case 0xC0B6:
            return "slmp_end_code_c0b6";
        case 0xC0BA:
            return "slmp_end_code_c0ba";
        case 0xC0C4:
            return "slmp_end_code_c0c4";
        case 0xC0D0:
            return "slmp_end_code_c0d0";
        case 0xC0D1:
            return "slmp_end_code_c0d1";
        case 0xC0D3:
            return "slmp_end_code_c0d3";
        case 0xC0D4:
            return "slmp_end_code_c0d4";
        case 0xC0D5:
            return "slmp_end_code_c0d5";
        case 0xC0D6:
            return "slmp_end_code_c0d6";
        case 0xC0D7:
            return "slmp_end_code_c0d7";
        case 0xC0D8:
            return "slmp_end_code_c0d8";
        case 0xC0D9:
            return "slmp_end_code_c0d9";
        case 0xC0DA:
            return "slmp_end_code_c0da";
        case 0xC0DB:
            return "slmp_end_code_c0db";
        case 0xC0DE:
            return "slmp_end_code_c0de";
        case 0xC101:
            return "slmp_end_code_c101";
        case 0xC1A2:
            return "slmp_end_code_c1a2";
        case 0xC1A4:
            return "slmp_end_code_c1a4";
        case 0xC1A5:
            return "slmp_end_code_c1a5";
        case 0xC1A6:
            return "slmp_end_code_c1a6";
        case 0xC1A7:
            return "slmp_end_code_c1a7";
        case 0xC1A8:
            return "slmp_end_code_c1a8";
        case 0xC1A9:
            return "slmp_end_code_c1a9";
        case 0xC1AA:
            return "slmp_end_code_c1aa";
        case 0xC1AC:
            return "slmp_end_code_c1ac";
        case 0xC1AD:
            return "slmp_end_code_c1ad";
        case 0xC1AF:
            return "slmp_end_code_c1af";
        case 0xC1B0:
            return "slmp_end_code_c1b0";
        case 0xC1B1:
            return "slmp_end_code_c1b1";
        case 0xC1B2:
            return "slmp_end_code_c1b2";
        case 0xC1B3:
            return "slmp_end_code_c1b3";
        case 0xC1B4:
            return "slmp_end_code_c1b4";
        case 0xC1B8:
            return "slmp_end_code_c1b8";
        case 0xC1B9:
            return "slmp_end_code_c1b9";
        case 0xC1BA:
            return "slmp_end_code_c1ba";
        case 0xC1BB:
            return "slmp_end_code_c1bb";
        case 0xC1BC:
            return "slmp_end_code_c1bc";
        case 0xC1BD:
            return "slmp_end_code_c1bd";
        case 0xC1BE:
            return "slmp_end_code_c1be";
        case 0xC1BF:
            return "slmp_end_code_c1bf";
        case 0xC1C0:
            return "slmp_end_code_c1c0";
        case 0xC1C1:
            return "slmp_end_code_c1c1";
        case 0xC1C2:
            return "slmp_end_code_c1c2";
        case 0xC1C4:
            return "slmp_end_code_c1c4";
        case 0xC1C5:
            return "slmp_end_code_c1c5";
        case 0xC1C6:
            return "slmp_end_code_c1c6";
        case 0xC1C7:
            return "slmp_end_code_c1c7";
        case 0xC1C8:
            return "slmp_end_code_c1c8";
        case 0xC1C9:
            return "slmp_end_code_c1c9";
        case 0xC1CA:
            return "slmp_end_code_c1ca";
        case 0xC1CB:
            return "slmp_end_code_c1cb";
        case 0xC1CC:
            return "slmp_end_code_c1cc";
        case 0xC1CD:
            return "slmp_end_code_c1cd";
        case 0xC1D0:
            return "slmp_end_code_c1d0";
        case 0xC1D2:
            return "slmp_end_code_c1d2";
        case 0xC1D3:
            return "slmp_end_code_c1d3";
        case 0xC200:
            return "slmp_end_code_c200";
        case 0xC201:
            return "slmp_end_code_c201";
        case 0xC202:
            return "slmp_end_code_c202";
        case 0xC203:
            return "slmp_end_code_c203";
        case 0xC204:
            return "slmp_end_code_c204";
        case 0xC205:
            return "slmp_end_code_c205";
        case 0xC207:
            return "slmp_end_code_c207";
        case 0xC208:
            return "slmp_end_code_c208";
        case 0xC400:
            return "slmp_end_code_c400";
        case 0xC401:
            return "slmp_end_code_c401";
        case 0xC402:
            return "slmp_end_code_c402";
        case 0xC403:
            return "slmp_end_code_c403";
        case 0xC404:
            return "slmp_end_code_c404";
        case 0xC405:
            return "slmp_end_code_c405";
        case 0xC406:
            return "slmp_end_code_c406";
        case 0xC407:
            return "slmp_end_code_c407";
        case 0xC408:
            return "slmp_end_code_c408";
        case 0xC410:
            return "slmp_end_code_c410";
        case 0xC412:
            return "slmp_end_code_c412";
        case 0xC413:
            return "slmp_end_code_c413";
        case 0xC414:
            return "slmp_end_code_c414";
        case 0xC417:
            return "slmp_end_code_c417";
        case 0xC420:
            return "slmp_end_code_c420";
        case 0xC421:
            return "slmp_end_code_c421";
        case 0xC430:
            return "slmp_end_code_c430";
        case 0xC431:
            return "slmp_end_code_c431";
        case 0xC440:
            return "slmp_end_code_c440";
        case 0xC441:
            return "slmp_end_code_c441";
        case 0xC442:
            return "slmp_end_code_c442";
        case 0xC443:
            return "slmp_end_code_c443";
        case 0xC444:
            return "slmp_end_code_c444";
        case 0xC445:
            return "slmp_end_code_c445";
        case 0xC446:
            return "slmp_end_code_c446";
        case 0xC447:
            return "slmp_end_code_c447";
        case 0xC448:
            return "slmp_end_code_c448";
        case 0xC449:
            return "slmp_end_code_c449";
        case 0xC44A:
            return "slmp_end_code_c44a";
        case 0xC44B:
            return "slmp_end_code_c44b";
        case 0xC44C:
            return "slmp_end_code_c44c";
        case 0xC44D:
            return "slmp_end_code_c44d";
        case 0xC44E:
            return "slmp_end_code_c44e";
        case 0xC44F:
            return "slmp_end_code_c44f";
        case 0xC610:
            return "slmp_end_code_c610";
        case 0xC611:
            return "slmp_end_code_c611";
        case 0xC612:
            return "slmp_end_code_c612";
        case 0xC613:
            return "slmp_end_code_c613";
        case 0xC614:
            return "slmp_end_code_c614";
        case 0xC615:
            return "slmp_end_code_c615";
        case 0xC616:
            return "slmp_end_code_c616";
        case 0xC617:
            return "slmp_end_code_c617";
        case 0xC618:
            return "slmp_end_code_c618";
        case 0xC619:
            return "slmp_end_code_c619";
        case 0xC620:
            return "slmp_end_code_c620";
        case 0xC621:
            return "slmp_end_code_c621";
        case 0xC622:
            return "slmp_end_code_c622";
        case 0xC623:
            return "slmp_end_code_c623";
        case 0xC700:
            return "slmp_end_code_c700";
        case 0xC701:
            return "slmp_end_code_c701";
        case 0xC702:
            return "slmp_end_code_c702";
        case 0xC703:
            return "slmp_end_code_c703";
        case 0xC704:
            return "slmp_end_code_c704";
        case 0xC705:
            return "slmp_end_code_c705";
        case 0xC706:
            return "slmp_end_code_c706";
        case 0xC707:
            return "slmp_end_code_c707";
        case 0xC708:
            return "slmp_end_code_c708";
        case 0xC709:
            return "slmp_end_code_c709";
        case 0xC810:
            return "slmp_end_code_c810";
        case 0xC811:
            return "slmp_end_code_c811";
        case 0xC812:
            return "slmp_end_code_c812";
        case 0xC813:
            return "slmp_end_code_c813";
        case 0xC814:
            return "slmp_end_code_c814";
        case 0xC815:
            return "slmp_end_code_c815";
        case 0xC816:
            return "slmp_end_code_c816";
        case 0xC840:
            return "slmp_end_code_c840";
        case 0xC842:
            return "slmp_end_code_c842";
        case 0xC843:
            return "slmp_end_code_c843";
        case 0xC844:
            return "slmp_end_code_c844";
        case 0xC860:
            return "slmp_end_code_c860";
        case 0xC861:
            return "slmp_end_code_c861";
        case 0xC862:
            return "slmp_end_code_c862";
        case 0xC863:
            return "slmp_end_code_c863";
        case 0xC864:
            return "slmp_end_code_c864";
        case 0xC865:
            return "slmp_end_code_c865";
        case 0xC866:
            return "slmp_end_code_c866";
        case 0xC867:
            return "slmp_end_code_c867";
        case 0xC868:
            return "slmp_end_code_c868";
        case 0xC869:
            return "slmp_end_code_c869";
        case 0xC86A:
            return "slmp_end_code_c86a";
        case 0xC86B:
            return "slmp_end_code_c86b";
        case 0xC86C:
            return "slmp_end_code_c86c";
        case 0xCEE0:
            return "slmp_end_code_cee0";
        case 0xCEE1:
            return "slmp_end_code_cee1";
        case 0xCEE2:
            return "slmp_end_code_cee2";
        case 0xCF10:
            return "slmp_end_code_cf10";
        case 0xCF20:
            return "slmp_end_code_cf20";
        case 0xCF30:
            return "slmp_end_code_cf30";
        case 0xCF31:
            return "slmp_end_code_cf31";
        case 0xCF70:
            return "slmp_end_code_cf70";
        case 0xCF71:
            return "slmp_end_code_cf71";
        case 0xCF80:
            return "slmp_end_code_cf80";
        case 0xCF81:
            return "slmp_end_code_cf81";
        case 0xCF82:
            return "slmp_end_code_cf82";
        case 0xCF83:
            return "slmp_end_code_cf83";
        case 0xCF84:
            return "slmp_end_code_cf84";
        case 0xCF85:
            return "slmp_end_code_cf85";
        case 0xCF8A:
            return "slmp_end_code_cf8a";
        case 0xCF8C:
            return "slmp_end_code_cf8c";
        case 0xCFB0:
            return "slmp_end_code_cfb0";
        case 0xCFB1:
            return "slmp_end_code_cfb1";
        case 0xCFB2:
            return "slmp_end_code_cfb2";
        case 0xCFB3:
            return "slmp_end_code_cfb3";
        case 0xCFB4:
            return "slmp_end_code_cfb4";
        case 0xCFB5:
            return "slmp_end_code_cfb5";
        case 0xCFBD:
            return "slmp_end_code_cfbd";
        case 0xCFBE:
            return "slmp_end_code_cfbe";
        case 0xCFBF:
            return "slmp_end_code_cfbf";
        default:
            return "unknown_plc_end_code";
    }
}

bool isRemotePasswordEndCode(uint16_t end_code) {
    switch (end_code) {
        case 0xC200:
        case 0xC201:
        case 0xC202:
        case 0xC203:
        case 0xC204:
        case 0xC205:
        case 0xC810:
        case 0xC811:
        case 0xC812:
        case 0xC813:
        case 0xC814:
        case 0xC815:
        case 0xC816:
            return true;
        default:
            return false;
    }
}

}  // namespace slmp
